--- #YAML:1.0
name:               Text-WordGrams
version:            0.03
abstract:           Calculates statistics on word ngrams.
author:
    - Alberto Simoes <ambs@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Lingua::PT::PLNbase:  0.02
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
